# Optional - if your git repo requires an SSH key.
git_private_key: |
   -----BEGIN RSA PRIVATE KEY-----
   MIIEpAIBAAKCAQEAqYRvh/MP8bticR4M95XfrB/TDIM41doRfPi/gVQKLtHrJQnJ
   ZZPsammf4272bBNLWOYFgwGC3D5FGiwB95qb5dWolnycELVyINpdiWLlopMVhMsu
   etzmUWgfn/vFTGP2gqfXX3EmLG2de0YoSh3+iHg4l2Hr2ammAueBriOGK0N2n2vv
   LkQSSSsYIp+i606Ax5BMMgYYfSBW9CMqwSoDSwxqXCI6ps5UZC/kDKWBWlvWjygV
   w94cvKzfO+J9EHk/do78b9Jiy9Xm6G1HoX3xNDn7YgGXFITbFQpw818PC5hbhgqf
   bIt218h5gjhyDy/+tvdIqD214Hytr1ExUOmdowIDAQABAoIBACQCsDavGbn+VoE1
   IwgNXICSGiFUVuSG+KQVq4jrs2YSzeMGWzQq4lQQsBh+X/bBeoYeBxm3Xncu+zr+
   EkTpISkH5FJjkjuyb9YuzSP8UE/i8vVMvEj5WCv+9Ijl0RnTOnCy+vuZa8SQXJ3t
   X22vRXz0HQF7mcCZW1zOlSvK/BuAVr0uTFbKsWvTJhXFBQEaDmgBIeRZ7enAA+O9
   e75HCMf6vDuZeQ32Ci9Dj4WIW3gReSKz+EZNhaM6H8Cls9urDzPoXDCWuWi0DIk+
   hI3kHyk7I76uPVtGm1OSnl3DeX0MTg1HPFDYcZP3TkNSn1/OcJW4sMVCuLQRQ3AW
   LUazoDECgYEA2nkSA0hilqkWkClLZrpzrM9S2yZW3F6/DF3bDSR+pfMZVv2HS1iy
   6l1v5H7NrX31+guB7cTOjkqDBi9iGypZjni0xrgFhpMIcxJwj6UGIwkmeEyWlKf5
   ilc4x2/5ry/sNucFcWehn0g2CdnvcwBmioHlCGwkZ5iTaYXPEtnCsEcCgYEAxqKi
   25YFOb/YLs+tjPMNEtG+YZvsrudKWXxnF0ELlruV4WvQNi75ZLTj/OLV3CogL1TP
   /V4YMzCrUbwLf3qJQpuq6eeOTcLMGxIiRWI3NO7nlUqPYW0YtZQwb5Vh7mS92VkC
   3s0u79zJOopxeWea7Lhpsisw6rZ/ix2Zjqdi0cUCgYEAyVoGKPJgsrxaKDl23dH/
   5IgbtBDMw0OrTol95sn405eOhicZt26jTu8Yvf3EMB7EQlSyxeG6AVhZE609/Q12
   BqHm8rMNnK8MfYnEJg+Q7V90jjEAIzgA++hRUzY3Z6eCTEN1N8SsJ7IU49VxI4t9
   9i+rV6zbjIMJcZq6c4QxM+cCgYEAjaLsc51ujnYwZXiqrMWmfdPXZ+xyAWllB5gA
   PoGgDNQnlHx3FBu8s0WVB/6LNhlHp9hXErhkkyPSFU779+NdOoSbg3wcaXBMb8Un
   cMgOy4zKzxZCVNsg8mD/hKFFGmL1SKUCufIe1ORfDIIpVcM9oiwBGg1YLRUCryTl
   GOZcPW0CgYAoI+efP3AigbUMv3813Njg8HSELU74bB/3jvg7jpn4/BZh1324TXNe
   iu83puoILjuMJhE2vTs9z1ihlGyNcY3BcyIEdSiq9NeWG560bhzuZW24NMznDVwM
   pMr40GlyWaTI5SCKTx8rLYc9SUQ2qrcz7M/NbaYWey+bOZrdc0JTJQ==
   -----END RSA PRIVATE KEY-----
