resources:
- name: ise-concourse
  type: git
  source:
    uri: git@github.com:MaheshRudrachar/ise-concourse.git
    branch: master
    private_key: {{git_private_key}}

jobs:
- name: upgrade-psn
  plan:
  - get: ise-concourse
  - task: deploy
    file: ise-pipeline/tasks/upgrade-psn/task.yml